(require 'avy)
(global-set-key (kbd "C-c SPC") 'avy-goto-char)
(global-set-key (kbd "C-c m SPC") 'avy-goto-char-2)
(global-set-key (kbd "C-c m m SPC") 'avy-goto-word-1)
(global-set-key (kbd "M-g g") 'avy-goto-line)
