(require 'helm-config)
(require 'helm-ls-git)
(require 'helm-swoop)
(require 'helm-gnu-global)
(setq helm-minibuffer-history-key nil)
(setq helm-truncate-lines t)
(setq helm-move-to-line-cycle-in-source t)
