;;; A few miscellaneous general keybindings: ;;;
(global-set-key (kbd "C-c m k") 'kill-buffer-and-window)
(global-set-key (kbd "<f5>") 'revert-buffer)
(global-set-key (kbd "<S-f5>") (lambda ()
                                 "revert buffer and go to end of buffer"
                                 (interactive)
                                 (revert-buffer)
                                 (end-of-buffer)))
;; (global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "M-/") 'dabbrev-expand)
(global-set-key (kbd "<f6>") 'next-error)
(global-set-key (kbd "<S-f6>") 'previous-error)
(global-set-key (kbd "<f7>") 'compile)
;; (setq my-test-loc "/home/mgalgs/src/Kasat/ncwaveform/Release/waveform/ModemController/test/")
;; (setq my-test-loc "/home/mgalgs/src/807/ncwaveform/Release/waveform/ModemController/test/")
(setq my-test-loc "/home/mgalgs/mnt/rugged2/mitch.humpherys/mh_NCWPLUS_funfest/Kasat/ncwaveform/Release/waveform/ModemController/test/")
(global-set-key (kbd "<C-f7>") (lambda ()
                                 (interactive)
                                 (my-compile-unit-tests my-test-loc "./rebuild.sh")))
(global-set-key (kbd "<S-f7>") (lambda ()
                                 (interactive)
                                 (my-compile-unit-tests my-test-loc "./build.sh")))
(global-set-key "\C-cmm" 'woman)

(global-set-key (kbd "C-<up>") 'my-up-a-line)
(global-set-key (kbd "M-P") 'my-up-a-line)
(global-set-key (kbd "C-<down>") 'my-down-a-line)
(global-set-key (kbd "M-N") 'my-down-a-line)
;; (global-set-key (kbd "C-M-{") 'my-up-5-lines)
;; (global-set-key (kbd "C-M-}") 'my-down-5-lines)
(global-set-key (kbd "C-S-l") 'my-horizontal-recenter)

;; iedit
(define-key global-map (kbd "C-;") 'iedit-mode)
(define-key isearch-mode-map (kbd "C-;") 'iedit-mode)
(global-set-key "\M-Y" 'yank-pop-forwards)
(global-set-key (kbd "C-c m g") 'grep-with-prefix-arg)
