(require 'rainbow-delimiters)
(set-face-attribute 'rainbow-delimiters-depth-1-face nil :foreground "#2aa198")
(set-face-attribute 'rainbow-delimiters-depth-2-face nil :foreground "#b58900")
(set-face-attribute 'rainbow-delimiters-depth-3-face nil :foreground "#268bd2")
(set-face-attribute 'rainbow-delimiters-depth-4-face nil :foreground "#dc322f")
(set-face-attribute 'rainbow-delimiters-depth-5-face nil :foreground "#859900")
(set-face-attribute 'rainbow-delimiters-depth-6-face nil :foreground "#268bd2")
(set-face-attribute 'rainbow-delimiters-depth-7-face nil :foreground "#cb4b16")
(set-face-attribute 'rainbow-delimiters-depth-8-face nil :foreground "#d33682")
(set-face-attribute 'rainbow-delimiters-depth-9-face nil :foreground "#839496")

(add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
(add-hook 'ielm-mode-hook 'rainbow-delimiters-mode)
